default:
	just --list

all:
	uv run benchmark.py --db ojdkchm_db ojdkchm_oa_db gsm_db gsm_diom_db gsm_ii_db gsm_diom_ii_db rwl_db --workload a b c d f --max 12 --trials 10
	uv run benchmark.py --db gsm_db gsm_diom_db gsm_diom_ii_db rwl_db --workload L --max 12 --trials 10
	uv run collect_stats.py
	uv run graph.py
